// Public gallery, souvenir, FAQ, and contact routes backed by the production Supabase schema.
import "./content-pages.css";
import { CheckCircle2, MessageCircle, Package, Send } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { loadFaqs, loadGallery, loadPublicSetting, loadSouvenirs, submitContact, subscribeToNewsletter, type Faq, type GalleryItem, type SouvenirPackage } from "@/lib/commerce";
import { PageHero, PublicShell } from "@/components/PublicShell";

export function GalleryPage() {
  const [items, setItems] = useState<GalleryItem[]>([]);
  useEffect(() => { loadGallery().then(setItems).catch(() => undefined); }, []);
  return <PublicShell><PageHero eyebrow="Visual archive" title={<>The details<br /><i>stay with you.</i></>}>A collection of packaging, gatherings, and grain details shared by Aboyejo Global Foods.</PageHero><section className="premium-content-section"><div className="premium-content-intro"><p className="premium-eyebrow">01 / The archive</p><p>Selected moments from the Aboyejo story, shared as they are published.</p></div>{items.length ? <div className="premium-gallery-grid">{items.map((item, index) => <figure className={`premium-gallery-card card-${(index % 4) + 1}`} key={item.id}><img src={item.image_url} alt={item.title} /><figcaption><span>0{index + 1}</span><div><strong>{item.title}</strong>{item.caption ? <p>{item.caption}</p> : null}</div></figcaption></figure>)}</div> : <EmptyNotice title="The gallery is being curated." text="New product and occasion imagery will appear here as it is published by the team." />}</section></PublicShell>;
}

export function SouvenirsPage() {
  const [items, setItems] = useState<SouvenirPackage[]>([]);
  useEffect(() => { loadSouvenirs().then(setItems).catch(() => undefined); }, []);
  return <PublicShell><PageHero eyebrow="The souvenir experience" title={<>Pack the occasion<br />with something <i>people know.</i></>}>Custom Aboyejo presentation for weddings, birthdays, naming ceremonies, churches, schools, corporate moments, and more.</PageHero><section className="premium-content-section"><div className="premium-content-intro split"><p className="premium-eyebrow">02 / Meaningful occasions</p><p>Choose a presentation starting point, then begin a direct conversation with the team.</p></div>{items.length ? <div className="premium-souvenir-grid">{items.map((item, index) => <article className="premium-souvenir-card" key={item.id}><div className="premium-souvenir-visual">{item.image_url ? <img src={item.image_url} alt={item.name} /> : <div className="premium-image-placeholder"><Package size={28} /></div>}<span>0{index + 1}</span></div><div className="premium-souvenir-copy"><p className="premium-eyebrow">{item.event_types.join(" · ")}</p><h2>{item.name}</h2><p>{item.description}</p><div className="premium-card-details">{item.minimum_quantity ? <span>Minimum quantity: {item.minimum_quantity}</span> : null}{item.price_note ? <span>{item.price_note}</span> : null}</div><Link className="premium-inline-link" href="/contact">Request a quote <b>↗</b></Link></div></article>)}</div> : <EmptyNotice title="Souvenir packages are being prepared." text="Start an enquiry to discuss custom packaging for your event." />}</section></PublicShell>;
}

export function FaqPage() {
  const [items, setItems] = useState<Faq[]>([]);
  useEffect(() => { loadFaqs().then(setItems).catch(() => undefined); }, []);
  return <PublicShell><PageHero eyebrow="Questions, answered" title={<>A clear next<br /><i>step.</i></>}>Everything here stays simple. If your question is more specific, the enquiry page is the quickest way to ask.</PageHero><section className="premium-content-section"><div className="premium-content-intro split"><p className="premium-eyebrow">03 / A simple answer</p><p>Start here, then contact the team if you would like to discuss a specific order or occasion.</p></div>{items.length ? <div className="premium-faq-list">{items.map((item, index) => <details key={item.id} open={index === 0}><summary><span>0{index + 1}</span><strong>{item.question}</strong><b>+</b></summary><p>{item.answer}</p></details>)}</div> : <EmptyNotice title="FAQs are being prepared." text="For a quick answer now, send a direct enquiry to the Aboyejo team." />}</section></PublicShell>;
}

export function ContactPage() {
  const [notice, setNotice] = useState("");
  const [whatsApp, setWhatsApp] = useState("");
  useEffect(() => { loadPublicSetting("whatsapp_number").then(setWhatsApp).catch(() => undefined); }, []);
  async function onContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await submitContact({ name: String(data.get("name") || ""), email: String(data.get("email") || ""), phone: String(data.get("phone") || ""), message: String(data.get("message") || "") }); setNotice("Thank you — your message has been received."); form.reset(); } catch { setNotice("Your message could not be sent right now. Please try again shortly."); } }
  async function onNewsletter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const email = String(new FormData(form).get("email") || ""); try { await subscribeToNewsletter(email); setNotice("You are on the Aboyejo newsletter list."); form.reset(); } catch { setNotice("We could not add that email just now."); } }
  const digits = whatsApp.replace(/\D/g, "");
  const whatsappHref = digits ? `https://wa.me/${digits}` : "";
  return <PublicShell><PageHero eyebrow="Order enquiry" title={<>Ready when<br /><i>you are.</i></>}>Tell the team what you are planning. Use the form for an enquiry, or WhatsApp when the live line has been configured.</PageHero><section className="premium-content-section"><div className="premium-content-intro split"><p className="premium-eyebrow">04 / Start the conversation</p><p>Share the details of your pantry order, occasion, or gifting plan. The team will respond through the channel you choose.</p></div><div className="premium-contact-grid"><form className="premium-contact-form" onSubmit={onContact}><div className="premium-form-heading"><MessageCircle size={20} /><div><p className="premium-eyebrow">Direct enquiry</p><h2>Tell us what you need.</h2></div></div><div className="premium-form-split"><label>Your name<input name="name" required placeholder="Full name" /></label><label>Phone number<input name="phone" placeholder="e.g. +234…" /></label></div><label>Email <span>(optional)</span><input type="email" name="email" placeholder="you@example.com" /></label><label>What are you planning?<textarea name="message" required rows={6} placeholder="Pantry order, occasion, gifting, or something else…" /></label><button className="premium-form-button" type="submit"><Send size={16} /> Send enquiry</button></form><aside className="premium-contact-aside"><p className="premium-eyebrow">Ordering channel</p><h2>WhatsApp, when you need it.</h2><p>For quick follow-up on products and occasions, the business keeps its live WhatsApp number in site settings.</p>{whatsappHref ? <a className="premium-whatsapp-action" href={whatsappHref} target="_blank" rel="noreferrer">Open WhatsApp</a> : <p className="premium-aside-notice">The WhatsApp line has not yet been published. Use the enquiry form instead.</p>}<form className="premium-newsletter-form" onSubmit={onNewsletter}><p className="premium-eyebrow">Newsletter</p><label>Email updates<input name="email" required type="email" placeholder="you@example.com" /></label><button type="submit">Subscribe</button></form>{notice ? <p className="premium-success-note"><CheckCircle2 size={17} /> {notice}</p> : null}</aside></div></section></PublicShell>;
}

function EmptyNotice({ title, text }: { title: string; text: string }) { return <div className="premium-empty-state"><p className="premium-eyebrow">Aboyejo Global Foods</p><h2>{title}</h2><p>{text}</p><Link className="premium-inline-link" href="/contact">Start an enquiry <b>↗</b></Link></div>; }
